# Segunda etapa: construye el backend
FROM python:3.9-alpine as backend

# Establece el directorio de trabajo para el backend
WORKDIR /app/backend

# Copia los archivos necesarios para el backend
COPY . .

RUN apk update && \
    apk add --no-cache npm nodejs

# Instala las dependencias
RUN pip install -r requirements.txt
