# Segunda etapa: construye el backend
FROM python:3.9-alpine as backend

# Establece el directorio de trabajo para el backend
WORKDIR /app/backend

# Copia los archivos necesarios para el backend
COPY . .

EXPOSE 3001

RUN pip install virtualenv
RUN virtualenv . --python=python3
RUN source ./bin/activate
RUN pip install -r requirements.txt

# RUN python manage.py makemigrations && python manage.py migrate
