# Generated by Django 4.1.5 on 2023-03-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='img',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
