# Generated by Django 4.1.5 on 2023-03-30 20:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_remove_profileusr_balance'),
        ('fields', '0003_field_pfh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_ini', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('date_fin', models.DateTimeField(default=datetime.datetime.now)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'reserve',
                'verbose_name_plural': 'reserves',
            },
        ),
    ]
