# Generated by Django 4.1.5 on 2023-05-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0002_reserve_status_alter_reserve_date_ini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=100),
        ),
    ]
