# Generated by Django 4.1.5 on 2023-03-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profileusr_notis'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileusr',
            name='balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
