# Generated by Django 4.1.5 on 2023-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_field_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='pfh',
            field=models.FloatField(blank=True, default=2),
        ),
    ]
